### ISSUE TITLE
Error: use sdk to create on-chain attestation

### ISSUE THREAD

**Issue by weiguangchao** [ethereum-attestation-service/eas-sdk#36]
i use sepolia testnet, code look like this:
```
import { EAS, SchemaEncoder } from "@ethereum-attestation-service/eas-sdk";

const eas = new EAS(EASContractAddress);
eas.connect(signer);

// Initialize SchemaEncoder with the schema string
const schemaEncoder = new SchemaEncoder("uint256 eventId, uint8 voteIndex");
const encodedData = schemaEncoder.encodeData([
  { name: "eventId", value: 1, type: "uint256" },
  { name: "voteIndex", value: 1, type: "uint8" },
]);

const schemaUID = "0xb16fa048b0d597f5a821747eba64efa4762ee5143e9a80600d0005386edfc995";

const tx = await eas.attest({
  schema: schemaUID,
  data: {
    recipient: "0xFD50b031E778fAb33DfD2Fc3Ca66a1EeF0652165",
    expirationTime: 0,
    revocable: true,
    data: encodedData,
  },
});

const newAttestationUID = await tx.wait();

console.log("New attestation UID:", newAttestationUID);
```

error:
```
Error: cannot estimate gas; transaction may fail or may require manual gas limit [ See: https://links.ethers.org/v5-errors-UNPREDICTABLE_GAS_LIMIT ] (error={"reason":"execution reverted","code":"UNPREDICTABLE_GAS_LIMIT","method":"estimateGas","transaction":{"from":"0xE65a34b090daF08C6C1eE4fDd35FCc5Ff794239C","maxPriorityFeePerGas":{"type":"BigNumber","hex":"0x59682f00"},"maxFeePerGas":{"type":"BigNumber","hex":"0x59682f12"},"to":"0xC2679fBD37d54388Ce493F1DB75320D236e1815e","data":"0xf17325e70000000000000000000000000000000000000000000000000000000000000020b1f077940c6b2d07d05412d11ef2c5bfd8fc9aadfc89ae87ec649640fc191e860000000000000000000000000000000000000000000000000000000000000040000000000000000000000000e65a34b090daf08c6c1ee4fdd35fcc5ff794239c00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000c00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000008000000000000000000000000000000000000000000000000000000000000000400000000000000000000000000000000000000000000000000000000000000012000000000000000000000000000000000000000000000000000000000000000562616a6965000000000000000000000000000000000000000000000000000000","type":2,"accessList":null}}, tx={"data":"0xf17325e70000000000000000000000000000000000000000000000000000000000000020b1f077940c6b2d07d05412d11ef2c5bfd8fc9aadfc89ae87ec649640fc191e860000000000000000000000000000000000000000000000000000000000000040000000000000000000000000e65a34b090daf08c6c1ee4fdd35fcc5ff794239c00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000c00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000008000000000000000000000000000000000000000000000000000000000000000400000000000000000000000000000000000000000000000000000000000000012000000000000000000000000000000000000000000000000000000000000000562616a6965000000000000000000000000000000000000000000000000000000","to":{},"from":"0xE65a34b090daF08C6C1eE4fDd35FCc5Ff794239C","type":2,"maxFeePerGas":{"type":"BigNumber","hex":"0x59682f12"},"maxPriorityFeePerGas":{"type":"BigNumber","hex":"0x59682f00"},"nonce":{},"gasLimit":{},"chainId":{}}, code=UNPREDICTABLE_GAS_LIMIT, version=abstract-signer/5.7.0)

    at Logger.Object.<anonymous>.Logger.makeError (/Users/weiguangchao/binglian/eas-demo/node_modules/@ethersproject/logger/src.ts/index.ts:269:28)
    at Logger.Object.<anonymous>.Logger.throwError (/Users/weiguangchao/binglian/eas-demo/node_modules/@ethersproject/logger/src.ts/index.ts:281:20)
    at /Users/weiguangchao/binglian/eas-demo/node_modules/@ethersproject/abstract-signer/src.ts/index.ts:301:31
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Promise.all (index 7)
```
and i also meet some error when use web app, link is https://sepolia.easscan.org/attestation/attestWithSchema/0xb1f077940c6b2d07d05412d11ef2c5bfd8fc9aadfc89ae87ec649640fc191e86

<img width="1862" alt="image" src="https://github.com/ethereum-attestation-service/eas-sdk/assets/42838365/ec7d7eab-dd23-4a09-a52a-8e747676f8c4">

thanks.

**Comment by weiguangchao** [comment]
i solve it. Because i setting a resolverAddress when create schema.
